export const quizData = {
  general: [
    { "question": "What is the capital of France?", "options": ["Berlin", "Madrid", "Paris", "Lisbon"], "correct": 2 },
    { "question": "Who wrote 'Hamlet'?", "options": ["Leo Tolstoy", "William Shakespeare", "Mark Twain", "Charles Dickens"], "correct": 1 },
    { "question": "What is the largest planet in our solar system?", "options": ["Earth", "Mars", "Jupiter", "Saturn"], "correct": 2 },
    { "question": "Who painted the Mona Lisa?", "options": ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Claude Monet"], "correct": 0 },
    { "question": "What is the chemical symbol for gold?", "options": ["Au", "Ag", "Pb", "Fe"], "correct": 0 },
    { "question": "What is the capital of Japan?", "options": ["Seoul", "Tokyo", "Beijing", "Bangkok"], "correct": 1 },
    { "question": "Who discovered gravity?", "options": ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"], "correct": 0 },
    { "question": "Which planet is known as the Red Planet?", "options": ["Earth", "Venus", "Mars", "Mercury"], "correct": 2 },
    { "question": "What is the largest mammal in the world?", "options": ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], "correct": 1 },
    { "question": "What year did World War II end?", "options": ["1940", "1945", "1950", "1939"], "correct": 1 },
    { "question": "What is the smallest country in the world?", "options": ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], "correct": 1 },
    { "question": "Who is known as the Father of Computers?", "options": ["Alan Turing", "Charles Babbage", "Steve Jobs", "Bill Gates"], "correct": 1 },
    { "question": "Which element has the chemical symbol 'O'?", "options": ["Oxygen", "Osmium", "Gold", "Helium"], "correct": 0 },
    { "question": "How many continents are there in the world?", "options": ["5", "6", "7", "8"], "correct": 2 },
    { "question": "What is the capital of Australia?", "options": ["Sydney", "Melbourne", "Canberra", "Perth"], "correct": 2 },
    { "question": "Who invented the telephone?", "options": ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "James Watt"], "correct": 0 },
    { "question": "What is the hardest natural substance on Earth?", "options": ["Gold", "Iron", "Diamond", "Quartz"], "correct": 2 },
    { "question": "What is the boiling point of water in Celsius?", "options": ["90°C", "100°C", "120°C", "80°C"], "correct": 1 },
    { "question": "Which is the longest river in the world?", "options": ["Amazon", "Nile", "Yangtze", "Mississippi"], "correct": 1 },
    { "question": "Who is the author of 'Harry Potter'?", "options": ["J.K. Rowling", "George R.R. Martin", "J.R.R. Tolkien", "Stephen King"], "correct": 0 },
    { "question": "What is the capital of the USA?", "options": ["Los Angeles", "Washington D.C.", "New York", "Chicago"], "correct": 1 },
    { "question": "Which ocean is the largest?", "options": ["Atlantic", "Indian", "Pacific", "Arctic"], "correct": 2 },
    { "question": "Who painted 'The Starry Night'?", "options": ["Vincent van Gogh", "Claude Monet", "Leonardo da Vinci", "Pablo Picasso"], "correct": 0 },
    { "question": "What gas do plants primarily absorb?", "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], "correct": 1 },
    { "question": "Which is the largest desert in the world?", "options": ["Sahara", "Arctic", "Gobi", "Kalahari"], "correct": 0 },
    { "question": "What is the square root of 64?", "options": ["6", "7", "8", "9"], "correct": 2 },
    { "question": "Which planet has the most moons?", "options": ["Jupiter", "Saturn", "Mars", "Uranus"], "correct": 1 },
    { "question": "Who was the first man to step on the moon?", "options": ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"], "correct": 1 },
    { "question": "What is the currency of the UK?", "options": ["Euro", "Dollar", "Pound Sterling", "Yen"], "correct": 2 },
    { "question": "Which is the largest bone in the human body?", "options": ["Femur", "Skull", "Humerus", "Tibia"], "correct": 0 },
    { "question": "What is the tallest mountain in the world?", "options": ["Mount Everest", "K2", "Kangchenjunga", "Lhotse"], "correct": 0 },
    { "question": "What does DNA stand for?", "options": ["Deoxyribonucleic Acid", "Ribonucleic Acid", "Nucleic Acid", "Deoxynucleic Ribosome"], "correct": 0 },
    { "question": "Who is the founder of Microsoft?", "options": ["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Larry Page"], "correct": 0 },
    { "question": "What is the capital of Canada?", "options": ["Toronto", "Ottawa", "Montreal", "Vancouver"], "correct": 1 },
    { "question": "Which country is known as the Land of the Rising Sun?", "options": ["China", "Japan", "Thailand", "Vietnam"], "correct": 1 },
    { "question": "What is the largest animal on land?", "options": ["Elephant", "Rhinoceros", "Giraffe", "Hippopotamus"], "correct": 0 },
    { "question": "Which year was the United Nations established?", "options": ["1940", "1945", "1950", "1960"], "correct": 1 },
    { "question": "What is the chemical formula for table salt?", "options": ["H2O", "NaCl", "CO2", "KCl"], "correct": 1 },
    { "question": "Who developed the theory of relativity?", "options": ["Albert Einstein", "Isaac Newton", "Stephen Hawking", "Marie Curie"], "correct": 0 },
    { "question": "Which bird is a universal symbol of peace?", "options": ["Dove", "Eagle", "Sparrow", "Parrot"], "correct": 0 }
  ],

  science: [
    {
      "question": "What is the chemical symbol for water?",
      "options": ["H2", "O2", "H2O", "HO2"],
      "correct": 2
    },
    {
      "question": "What planet is known as the Red Planet?",
      "options": ["Mars", "Earth", "Jupiter", "Venus"],
      "correct": 0
    },
    {
      "question": "What gas do plants primarily absorb for photosynthesis?",
      "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Methane"],
      "correct": 1
    },
    {
      "question": "What force keeps us on the ground?",
      "options": ["Magnetism", "Friction", "Gravity", "Centrifugal Force"],
      "correct": 2
    },
    {
      "question": "Who developed the theory of relativity?",
      "options": ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Marie Curie"],
      "correct": 1
    },
    {
      "question": "What part of the cell contains the genetic material?",
      "options": ["Nucleus", "Ribosome", "Mitochondria", "Golgi Apparatus"],
      "correct": 0
    },
    {
      "question": "What is the SI unit of force?",
      "options": ["Pascal", "Newton", "Joule", "Watt"],
      "correct": 1
    },
    {
      "question": "Which element has the atomic number 1?",
      "options": ["Oxygen", "Hydrogen", "Helium", "Lithium"],
      "correct": 1
    },
    {
      "question": "What type of blood cells fight infections?",
      "options": ["Red Blood Cells", "Platelets", "White Blood Cells", "Plasma"],
      "correct": 2
    },
    {
      "question": "What is the main gas found in Earth's atmosphere?",
      "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
      "correct": 2
    },
    {
      "question": "What is the process by which plants make food?",
      "options": ["Respiration", "Photosynthesis", "Digestion", "Transpiration"],
      "correct": 1
    },
    {
      "question": "Which planet has the most moons?",
      "options": ["Mars", "Jupiter", "Saturn", "Earth"],
      "correct": 1
    },
    {
      "question": "What is the basic unit of life?",
      "options": ["Atom", "Molecule", "Cell", "Organ"],
      "correct": 2
    },
    {
      "question": "What is the speed of light in a vacuum?",
      "options": ["300,000 km/s", "150,000 km/s", "100,000 km/s", "1,000 km/s"],
      "correct": 0
    },
    {
      "question": "What is the chemical symbol for gold?",
      "options": ["Au", "Ag", "Fe", "Go"],
      "correct": 0
    },
    {
      "question": "What type of energy is stored in a battery?",
      "options": ["Kinetic Energy", "Thermal Energy", "Chemical Energy", "Electrical Energy"],
      "correct": 2
    },
    {
      "question": "What is the smallest particle of an element?",
      "options": ["Molecule", "Atom", "Electron", "Proton"],
      "correct": 1
    },
    {
      "question": "Which organ pumps blood in the human body?",
      "options": ["Lungs", "Brain", "Heart", "Liver"],
      "correct": 2
    },
    {
      "question": "Which gas is most responsible for the greenhouse effect?",
      "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Methane"],
      "correct": 1
    },
    {
      "question": "What is the primary source of energy for the Earth?",
      "options": ["The Moon", "The Sun", "Geothermal Heat", "Nuclear Power"],
      "correct": 1
    },
    {
      "question": "What is the center of an atom called?",
      "options": ["Proton", "Nucleus", "Electron", "Molecule"],
      "correct": 1
    },
    {
      "question": "What is Newton's Third Law of Motion?",
      "options": ["F=ma", "For every action, there is an equal and opposite reaction", "Objects in motion stay in motion", "Energy cannot be created or destroyed"],
      "correct": 1
    },
    {
      "question": "What is the chemical formula for table salt?",
      "options": ["NaCl", "H2O", "CO2", "KCl"],
      "correct": 0
    },
    {
      "question": "What is the powerhouse of the cell?",
      "options": ["Nucleus", "Ribosome", "Mitochondria", "Chloroplast"],
      "correct": 2
    },
    {
      "question": "What is the freezing point of water?",
      "options": ["0°C", "32°F", "Both", "None"],
      "correct": 2
    }
  ],
  sports: [
    { "question": "How many players are there in a soccer team?", "options": ["9", "10", "11", "12"], "correct": 2 },
    { "question": "Which country won the FIFA World Cup in 2018?", "options": ["Brazil", "Germany", "France", "Argentina"], "correct": 2 },
    { "question": "In which year were the first modern Olympic Games held?", "options": ["1896", "1900", "1912", "1924"], "correct": 0 },
    { "question": "Who holds the record for the most goals in World Cup history?", "options": ["Pele", "Ronaldo", "Miroslav Klose", "Lionel Messi"], "correct": 2 },
    { "question": "Which sport is known as 'The King of Sports'?", "options": ["Football", "Cricket", "Basketball", "Tennis"], "correct": 0 },
    { "question": "Who won the NBA MVP Award in 2021?", "options": ["LeBron James", "Stephen Curry", "Giannis Antetokounmpo", "Nikola Jokic"], "correct": 3 },
    { "question": "How many minutes are there in a standard NBA game?", "options": ["36", "48", "60", "72"], "correct": 1 },
    { "question": "Which country hosted the 2016 Summer Olympics?", "options": ["China", "United Kingdom", "Brazil", "Greece"], "correct": 2 },
    { "question": "In which year did the first FIFA World Cup take place?", "options": ["1920", "1930", "1940", "1950"], "correct": 1 },
    { "question": "Which country won the 2003 Rugby World Cup?", "options": ["England", "Australia", "South Africa", "New Zealand"], "correct": 0 },
    { "question": "Which sport is Serena Williams famous for?", "options": ["Tennis", "Badminton", "Table Tennis", "Basketball"], "correct": 0 },
    { "question": "How many Grand Slam tennis titles has Roger Federer won?", "options": ["18", "19", "20", "21"], "correct": 2 },
    { "question": "Who holds the record for most career home runs in Major League Baseball?", "options": ["Barry Bonds", "Babe Ruth", "Hank Aaron", "Willie Mays"], "correct": 0 },
    { "question": "Which sport uses a puck?", "options": ["Basketball", "Football", "Hockey", "Baseball"], "correct": 2 },
    { "question": "Who won the 2019 ICC Cricket World Cup?", "options": ["India", "Australia", "England", "New Zealand"], "correct": 2 },
    { "question": "What is the national sport of Japan?", "options": ["Sumo Wrestling", "Judo", "Baseball", "Karate"], "correct": 0 },
    { "question": "How long is an NFL game?", "options": ["30 minutes", "45 minutes", "60 minutes", "90 minutes"], "correct": 2 },
    { "question": "Which country is known as the birthplace of rugby?", "options": ["New Zealand", "South Africa", "Australia", "England"], "correct": 3 },
    { "question": "What color is the jersey worn by the winner of the Tour de France?", "options": ["Green", "Yellow", "Red", "White"], "correct": 1 },
    { "question": "Which city hosted the 2008 Summer Olympics?", "options": ["London", "Tokyo", "Beijing", "Athens"], "correct": 2 },
    { "question": "What is the name of the NBA team based in Los Angeles?", "options": ["Lakers", "Heat", "Celtics", "Knicks"], "correct": 0 },
    { "question": "How many players are on a cricket team?", "options": ["9", "10", "11", "12"], "correct": 2 },
    { "question": "Who has won the most Formula 1 World Championships?", "options": ["Ayrton Senna", "Michael Schumacher", "Lewis Hamilton", "Sebastian Vettel"], "correct": 1 },
    { "question": "Which country is the host for the 2022 FIFA World Cup?", "options": ["Russia", "Qatar", "Brazil", "France"], "correct": 1 },
    { "question": "Who holds the record for the most goals scored in a single season of the English Premier League?", "options": ["Mohamed Salah", "Wayne Rooney", "Alan Shearer", "Sergio Agüero"], "correct": 0 },
    { "question": "In which year did the Chicago Cubs win the World Series after a 108-year drought?", "options": ["2012", "2014", "2016", "2018"], "correct": 2 },
    { "question": "What is the maximum weight allowed for a boxing heavyweight?", "options": ["175 lbs", "190 lbs", "210 lbs", "Over 200 lbs"], "correct": 3 },
    { "question": "Who won the 2020 UEFA Champions League?", "options": ["Bayern Munich", "Paris Saint-Germain", "Real Madrid", "Liverpool"], "correct": 0 },
    { "question": "Which tennis tournament is played on grass courts?", "options": ["Australian Open", "French Open", "US Open", "Wimbledon"], "correct": 3 },
    { "question": "Which country is the current holder of the Rugby World Cup?", "options": ["South Africa", "England", "New Zealand", "Australia"], "correct": 0 },
    { "question": "What sport does Usain Bolt compete in?", "options": ["Basketball", "Football", "Athletics", "Tennis"], "correct": 2 },
    { "question": "Which NFL team won the Super Bowl in 2020?", "options": ["New England Patriots", "Kansas City Chiefs", "San Francisco 49ers", "Los Angeles Rams"], "correct": 1 },
    { "question": "How many sets are played in a tennis match for men in Grand Slam tournaments?", "options": ["3", "4", "5", "6"], "correct": 2 },
    { "question": "What is the name of the trophy awarded to the winner of the English Premier League?", "options": ["FA Cup", "Premier League Trophy", "Carabao Cup", "Community Shield"], "correct": 1 },
    { "question": "Which country has won the most Olympic gold medals?", "options": ["United States", "China", "Russia", "Germany"], "correct": 0 },
    { "question": "Who is the all-time top scorer in the NBA?", "options": ["Michael Jordan", "Kareem Abdul-Jabbar", "LeBron James", "Kobe Bryant"], "correct": 1 },
    { "question": "Which sport is Tiger Woods famous for?", "options": ["Golf", "Tennis", "Basketball", "Boxing"], "correct": 0 },
    { "question": "Which team won the 2021 UEFA Champions League?", "options": ["Chelsea", "Manchester City", "Bayern Munich", "Barcelona"], "correct": 0 },
    { "question": "Which city hosted the 2012 Summer Olympics?", "options": ["London", "Beijing", "Athens", "Sydney"], "correct": 0 },
    { "question": "How many players are there on a rugby team?", "options": ["11", "13", "15", "17"], "correct": 2 },
    { "question": "Which country has won the most FIFA Women's World Cup titles?", "options": ["USA", "Germany", "Brazil", "Norway"], "correct": 0 },
    { "question": "Who is considered the greatest swimmer of all time?", "options": ["Michael Phelps", "Ian Thorpe", "Caeleb Dressel", "Mark Spitz"], "correct": 0 },
    { "question": "In which country did the 2010 FIFA World Cup take place?", "options": ["Brazil", "Germany", "South Africa", "Argentina"], "correct": 2 },
    { "question": "What is the maximum weight for a lightweight boxer?", "options": ["115 lbs", "130 lbs", "140 lbs", "155 lbs"], "correct": 1 },
    { "question": "Which basketball player has the most career points?", "options": ["Kobe Bryant", "LeBron James", "Michael Jordan", "Karl Malone"], "correct": 1 },
    { "question": "Who won the 2014 FIFA World Cup?", "options": ["Argentina", "Brazil", "Germany", "Spain"], "correct": 2 },
    { "question": "Who holds the record for most home runs in a single MLB season?", "options": ["Barry Bonds", "Mark McGwire", "Sammy Sosa", "Hank Aaron"], "correct": 0 },
    { "question": "In which sport would you perform a slam dunk?", "options": ["Basketball", "Football", "Baseball", "Tennis"], "correct": 0 }
  ],
  history: [
    { "question": "Who was the first President of the United States?", "options": ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"], "correct": 1 },
    { "question": "In what year did World War II end?", "options": ["1942", "1945", "1948", "1950"], "correct": 1 },
    { "question": "Who was the first woman to fly solo across the Atlantic Ocean?", "options": ["Amelia Earhart", "Bessie Coleman", "Sally Ride", "Harriet Quimby"], "correct": 0 },
    { "question": "Which country was the first to grant women the right to vote?", "options": ["United States", "United Kingdom", "New Zealand", "France"], "correct": 2 },
    { "question": "Who was the leader of the Soviet Union during World War II?", "options": ["Joseph Stalin", "Leon Trotsky", "Nikita Khrushchev", "Mikhail Gorbachev"], "correct": 0 },
    { "question": "In what year did the Berlin Wall fall?", "options": ["1989", "1991", "1985", "1979"], "correct": 0 },
    { "question": "Who was the last Queen of France before the French Revolution?", "options": ["Marie Antoinette", "Catherine de' Medici", "Anne of Austria", "Isabella of Spain"], "correct": 0 },
    { "question": "Who discovered America?", "options": ["Christopher Columbus", "Leif Erikson", "Ferdinand Magellan", "John Cabot"], "correct": 0 },
    { "question": "Which empire was ruled by Julius Caesar?", "options": ["Roman Empire", "Ottoman Empire", "Mongol Empire", "British Empire"], "correct": 0 },
    { "question": "Which ancient civilization built the pyramids of Giza?", "options": ["Egyptians", "Greeks", "Romans", "Babylonians"], "correct": 0 },
    { "question": "Who was the first emperor of China?", "options": ["Qin Shi Huang", "Han Wudi", "Emperor Taizong", "Emperor Gaozu"], "correct": 0 },
    { "question": "What year did the Titanic sink?", "options": ["1905", "1912", "1920", "1898"], "correct": 1 },
    { "question": "Which war was fought between the North and South regions of the United States?", "options": ["American Revolution", "World War I", "American Civil War", "Spanish-American War"], "correct": 2 },
    { "question": "Who was the first man to walk on the moon?", "options": ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "Michael Collins"], "correct": 0 },
    { "question": "What ancient city is famous for its Hanging Gardens, one of the Seven Wonders?", "options": ["Babylon", "Athens", "Rome", "Alexandria"], "correct": 0 },
    { "question": "Who was the famous leader of the Mongol Empire?", "options": ["Genghis Khan", "Kublai Khan", "Attila the Hun", "Alexander the Great"], "correct": 0 },
    { "question": "Which battle marked the turning point of the American Revolution?", "options": ["Battle of Saratoga", "Battle of Bunker Hill", "Battle of Lexington", "Battle of Yorktown"], "correct": 0 },
    { "question": "In which year did the United States gain independence from Britain?", "options": ["1776", "1783", "1801", "1812"], "correct": 0 },
    { "question": "What was the first country to grant universal suffrage?", "options": ["United States", "New Zealand", "United Kingdom", "Australia"], "correct": 1 },
    { "question": "Which country was the first to land on the moon?", "options": ["USA", "Soviet Union", "China", "India"], "correct": 0 },
    { "question": "Who was the first female Prime Minister of the United Kingdom?", "options": ["Margaret Thatcher", "Theresa May", "Victoria", "Queen Elizabeth"], "correct": 0 },
    { "question": "Who wrote the 'Iliad' and the 'Odyssey'?", "options": ["Homer", "Socrates", "Plato", "Aristotle"], "correct": 0 },
    { "question": "Which event started World War I?", "options": ["Assassination of Archduke Franz Ferdinand", "Bombing of Pearl Harbor", "Invasion of Poland", "Attack on the World Trade Center"], "correct": 0 },
    { "question": "In which year did the French Revolution begin?", "options": ["1789", "1799", "1776", "1812"], "correct": 0 },
    { "question": "Which civilization built Machu Picchu?", "options": ["Maya", "Inca", "Aztec", "Olmec"], "correct": 1 },
    { "question": "Which city was the capital of the Roman Empire?", "options": ["Rome", "Athens", "Carthage", "Alexandria"], "correct": 0 },
    { "question": "Who was the famous Egyptian queen who had a relationship with Julius Caesar?", "options": ["Cleopatra", "Nefertiti", "Hatshepsut", "Maatkare"], "correct": 0 },
    { "question": "What was the name of the ship that brought the Pilgrims to America in 1620?", "options": ["Mayflower", "Santa Maria", "Discovery", "Endeavour"], "correct": 0 },
    { "question": "What event led to the start of World War II?", "options": ["Invasion of Poland", "Attack on Pearl Harbor", "Invasion of France", "The Treaty of Versailles"], "correct": 0 },
    { "question": "Which U.S. president delivered the Gettysburg Address?", "options": ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "Andrew Johnson"], "correct": 0 },
    { "question": "Who was the leader of the Nazis during World War II?", "options": ["Adolf Hitler", "Joseph Stalin", "Benito Mussolini", "Franklin D. Roosevelt"], "correct": 0 },
    { "question": "In which year did the Cold War end?", "options": ["1989", "1991", "1979", "1963"], "correct": 1 },
    { "question": "Which civilization is known for creating the first written language?", "options": ["Sumerians", "Romans", "Egyptians", "Greeks"], "correct": 0 },
    { "question": "Who was the leader of India during its independence in 1947?", "options": ["Jawaharlal Nehru", "Mahatma Gandhi", "Indira Gandhi", "Subhas Chandra Bose"], "correct": 0 },
    { "question": "Who was the last emperor of the Roman Empire?", "options": ["Romulus Augustulus", "Julius Caesar", "Augustus", "Tiberius"], "correct": 0 },
    { "question": "Who was the first emperor of Rome?", "options": ["Julius Caesar", "Augustus", "Nero", "Caligula"], "correct": 1 },
    { "question": "Which war took place between 1950 and 1953 on the Korean Peninsula?", "options": ["Vietnam War", "Korean War", "Cold War", "World War II"], "correct": 1 },
    { "question": "Which ancient civilization is famous for creating the wheel?", "options": ["Sumerians", "Romans", "Egyptians", "Greeks"], "correct": 0 },
    { "question": "In which year was the Magna Carta signed?", "options": ["1215", "1225", "1300", "1400"], "correct": 0 },
    { "question": "Who was the first man to set foot on the moon?", "options": ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"], "correct": 0 },
    { "question": "What ancient empire was known for building roads across its territory?", "options": ["Roman Empire", "Mongol Empire", "Ottoman Empire", "Mayan Empire"], "correct": 0 },
    { "question": "What year did the United States enter World War I?", "options": ["1914", "1916", "1917", "1918"], "correct": 2 },
    { "question": "Which leader is associated with the Cuban Revolution?", "options": ["Fidel Castro", "Che Guevara", "Juan Perón", "Salvador Allende"], "correct": 0 }
  ],
  math: [

    { "question": "What is 5 + 7?", "options": ["12", "15", "11", "13"], "correct": 0 },
    { "question": "What is 9 - 3?", "options": ["6", "5", "4", "7"], "correct": 0 },
    { "question": "What is 8 * 6?", "options": ["48", "44", "50", "42"], "correct": 0 },
    { "question": "What is 36 ÷ 4?", "options": ["9", "8", "7", "6"], "correct": 0 },
    { "question": "What is the square root of 81?", "options": ["9", "8", "10", "7"], "correct": 0 },
    { "question": "What is 15 + 8?", "options": ["23", "22", "24", "21"], "correct": 0 },
    { "question": "What is 16 - 7?", "options": ["9", "8", "7", "6"], "correct": 0 },
    { "question": "What is 5 * 9?", "options": ["45", "50", "40", "42"], "correct": 0 },
    { "question": "What is 49 ÷ 7?", "options": ["7", "6", "8", "9"], "correct": 0 },
    { "question": "What is the square root of 64?", "options": ["8", "6", "7", "9"], "correct": 0 },
    { "question": "What is 12 + 19?", "options": ["31", "30", "32", "33"], "correct": 0 },
    { "question": "What is 27 - 15?", "options": ["12", "14", "11", "13"], "correct": 0 },
    { "question": "What is 7 * 7?", "options": ["49", "48", "47", "50"], "correct": 0 },
    { "question": "What is 56 ÷ 8?", "options": ["7", "6", "8", "9"], "correct": 0 },
    { "question": "What is the square root of 100?", "options": ["10", "12", "11", "9"], "correct": 0 },
    { "question": "What is 25 + 30?", "options": ["55", "60", "50", "45"], "correct": 0 },
    { "question": "What is 18 - 5?", "options": ["13", "12", "14", "15"], "correct": 0 },
    { "question": "What is 11 * 8?", "options": ["88", "90", "92", "84"], "correct": 0 },
    { "question": "What is 72 ÷ 9?", "options": ["8", "9", "7", "10"], "correct": 0 },
    { "question": "What is the square root of 144?", "options": ["12", "14", "10", "13"], "correct": 0 },
    { "question": "What is 20 + 25?", "options": ["45", "50", "55", "60"], "correct": 0 },
    { "question": "What is 40 - 15?", "options": ["25", "30", "35", "20"], "correct": 0 },
    { "question": "What is 6 * 11?", "options": ["66", "60", "70", "65"], "correct": 0 },
    { "question": "What is 100 ÷ 25?", "options": ["4", "5", "6", "3"], "correct": 1 },
    { "question": "What is the square root of 49?", "options": ["7", "6", "8", "9"], "correct": 0 },
    { "question": "What is 5 * 12?", "options": ["60", "50", "55", "65"], "correct": 0 },
    { "question": "What is 80 ÷ 16?", "options": ["5", "6", "7", "4"], "correct": 0 },
    { "question": "What is the square root of 121?", "options": ["11", "10", "12", "9"], "correct": 0 },
    { "question": "What is 14 + 27?", "options": ["41", "42", "43", "40"], "correct": 0 },
    { "question": "What is 56 - 34?", "options": ["22", "23", "21", "20"], "correct": 0 },
    { "question": "What is 6 * 6?", "options": ["36", "38", "40", "35"], "correct": 0 },
    { "question": "What is 63 ÷ 9?", "options": ["7", "8", "9", "6"], "correct": 0 },
    { "question": "What is the square root of 169?", "options": ["13", "14", "12", "11"], "correct": 0 },
    { "question": "What is 19 + 21?", "options": ["40", "41", "42", "39"], "correct": 0 },
    { "question": "What is 33 - 17?", "options": ["16", "17", "15", "13"], "correct": 0 },
    { "question": "What is 9 * 8?", "options": ["72", "71", "70", "74"], "correct": 0 },
    { "question": "What is 72 ÷ 6?", "options": ["12", "13", "11", "10"], "correct": 0 },
    { "question": "What is the square root of 196?", "options": ["14", "15", "13", "16"], "correct": 0 },
    { "question": "What is 13 + 29?", "options": ["42", "41", "40", "43"], "correct": 0 },
    { "question": "What is 57 - 29?", "options": ["28", "29", "27", "30"], "correct": 0 },
    { "question": "What is 4 * 15?", "options": ["60", "55", "65", "70"], "correct": 0 },
    { "question": "What is 120 ÷ 30?", "options": ["4", "5", "6", "3"], "correct": 1 },
    { "question": "What is the square root of 256?", "options": ["16", "15", "17", "14"], "correct": 0 },
    { "question": "What is 22 + 18?", "options": ["40", "41", "42", "39"], "correct": 0 },
    { "question": "What is 85 - 46?", "options": ["39", "40", "41", "38"], "correct": 0 },
    { "question": "What is 7 * 13?", "options": ["91", "90", "92", "89"], "correct": 0 },
    { "question": "What is 144 ÷ 12?", "options": ["12", "11", "10", "13"], "correct": 0 },
    { "question": "What is the square root of 225?", "options": ["15", "16", "14", "17"], "correct": 0 },
    { "question": "What is 8 + 37?", "options": ["45", "46", "47", "44"], "correct": 0 },
    { "question": "What is 9 * 11?", "options": ["99", "100", "101", "98"], "correct": 0 },
    { "question": "What is 28 ÷ 4?", "options": ["7", "8", "6", "9"], "correct": 0 },
    { "question": "What is 19 * 3?", "options": ["57", "58", "56", "55"], "correct": 0 },
    { "question": "What is the square root of 36?", "options": ["6", "7", "5", "8"], "correct": 0 },
    { "question": "What is 53 + 9?", "options": ["62", "61", "60", "63"], "correct": 0 },
    { "question": "What is 100 - 36?", "options": ["64", "63", "65", "66"], "correct": 0 },
    { "question": "What is 6 * 10?", "options": ["60", "65", "62", "55"], "correct": 0 },
    { "question": "What is 120 ÷ 8?", "options": ["15", "16", "14", "13"], "correct": 0 },
    { "question": "What is 30 + 45?", "options": ["75", "74", "76", "77"], "correct": 0 },
    { "question": "What is 80 - 24?", "options": ["56", "57", "58", "59"], "correct": 0 },
    { "question": "What is 5 * 13?", "options": ["65", "63", "60", "68"], "correct": 0 },
    { "question": "What is 72 ÷ 8?", "options": ["9", "8", "7", "6"], "correct": 0 },
    { "question": "What is the square root of 144?", "options": ["12", "14", "13", "11"], "correct": 0 },
    { "question": "What is 35 + 22?", "options": ["57", "56", "58", "59"], "correct": 0 },
    { "question": "What is 63 - 14?", "options": ["49", "50", "51", "52"], "correct": 0 },
    { "question": "What is 12 * 12?", "options": ["144", "140", "145", "130"], "correct": 0 },
    { "question": "What is 96 ÷ 12?", "options": ["8", "7", "9", "6"], "correct": 0 }
  ],
  logical: [
    { "question": "What comes next in the sequence: 2, 4, 8, 16, ?", "options": ["32", "24", "48", "30"], "correct": 0 },
    { "question": "Which number is the odd one out: 3, 7, 11, 14, 17?", "options": ["14", "11", "7", "3"], "correct": 0 },
    { "question": "If two is company and three is a crowd, what is four and five?", "options": ["Nine", "A party", "Eleven", "A family"], "correct": 0 },
    { "question": "If some cats are dogs and some dogs are birds, can some birds be cats?", "options": ["No", "Yes", "Depends", "None of the above"], "correct": 0 },
    { "question": "Which of these is the largest number: 1/4, 1/3, 1/2, 1/5?", "options": ["1/2", "1/3", "1/5", "1/4"], "correct": 0 },
    { "question": "What comes next in the pattern: 1, 4, 9, 16, ?", "options": ["25", "36", "20", "10"], "correct": 0 },
    { "question": "Which of the following is not a primary color?", "options": ["Green", "Red", "Blue", "Yellow"], "correct": 0 },
    { "question": "Which number is missing in this sequence: 2, 4, 8, 16, ?, 64", "options": ["32", "48", "24", "40"], "correct": 0 },
    { "question": "If you have a cake and you cut it into 4 pieces, how many cuts were needed?", "options": ["3", "4", "2", "5"], "correct": 0 },
    { "question": "Which one of these does not belong: Car, Bus, Bicycle, Airplane?", "options": ["Bicycle", "Bus", "Car", "Airplane"], "correct": 0 },
    { "question": "If all roses are flowers, and some flowers are red, can some roses be red?", "options": ["Yes", "No", "Not enough information", "None of the above"], "correct": 0 },
    { "question": "What is the next number in the sequence: 2, 5, 8, 11, ?", "options": ["14", "15", "12", "10"], "correct": 0 },
    { "question": "Which number should replace the question mark: 6, 11, 16, ?, 26", "options": ["21", "19", "18", "20"], "correct": 0 },
    { "question": "Which letter is the next in the sequence: A, C, E, G, ?", "options": ["I", "H", "J", "K"], "correct": 0 },
    { "question": "Which is the odd one out: Circle, Square, Triangle, Rectangle?", "options": ["Circle", "Rectangle", "Square", "Triangle"], "correct": 0 },
    { "question": "If you have 2 apples and give away 1, how many apples do you have left?", "options": ["1", "2", "3", "0"], "correct": 0 },
    { "question": "What is the next number in the series: 3, 6, 9, 12, ?", "options": ["15", "18", "14", "13"], "correct": 0 },
    { "question": "If all birds can fly and all sparrows are birds, can all sparrows fly?", "options": ["Yes", "No", "Depends", "Not enough information"], "correct": 0 },
    { "question": "Which number does not belong: 12, 18, 24, 32, 36?", "options": ["32", "24", "18", "12"], "correct": 0 },
    { "question": "If 3 cats catch 3 mice in 3 minutes, how many cats catch 6 mice in 6 minutes?", "options": ["3", "6", "9", "2"], "correct": 1 },
    { "question": "Which of the following is the odd one out: Apple, Banana, Cherry, Carrot?", "options": ["Carrot", "Apple", "Banana", "Cherry"], "correct": 0 },
    { "question": "If you multiply two odd numbers, is the product odd or even?", "options": ["Odd", "Even", "It depends", "None of the above"], "correct": 0 },
    { "question": "What comes next in the sequence: 5, 10, 15, 20, ?", "options": ["25", "30", "35", "28"], "correct": 0 },
    { "question": "If all books are novels, and all novels are stories, can all books be stories?", "options": ["Yes", "No", "Maybe", "Not enough information"], "correct": 0 },
    { "question": "Which of these is the odd one out: Dog, Cat, Bird, Lion, Fish?", "options": ["Fish", "Bird", "Dog", "Cat"], "correct": 0 },
    { "question": "What comes next in the sequence: 1, 2, 4, 8, 16, ?", "options": ["32", "24", "40", "30"], "correct": 0 },
    { "question": "Which number is missing in the sequence: 3, 6, 9, ?, 15", "options": ["12", "10", "14", "13"], "correct": 0 },
    { "question": "If a clock shows 3:00 and you add 3 hours, what time is it?", "options": ["6:00", "5:00", "7:00", "8:00"], "correct": 0 },
    { "question": "If a train travels at 60 km/h, how far will it travel in 3 hours?", "options": ["180 km", "150 km", "170 km", "160 km"], "correct": 0 },
    { "question": "What comes next in the sequence: 10, 20, 30, 40, ?", "options": ["50", "45", "60", "55"], "correct": 0 },
    { "question": "If a box contains 5 red balls and 5 blue balls, what is the probability of picking a red ball?", "options": ["1/2", "1/5", "1/10", "1/4"], "correct": 0 },
    { "question": "Which number is missing in this sequence: 3, 6, 9, ?, 15, 18", "options": ["12", "10", "13", "11"], "correct": 0 },
    { "question": "Which number completes the sequence: 1, 4, 9, 16, ?, 36", "options": ["25", "24", "23", "22"], "correct": 0 },
    { "question": "Which of these is a multiple of 7: 49, 50, 51, 52?", "options": ["49", "50", "51", "52"], "correct": 0 },
    { "question": "Which is the odd one out: Dog, Tiger, Lion, Zebra?", "options": ["Zebra", "Dog", "Lion", "Tiger"], "correct": 0 },
    { "question": "If 2 pens cost 50 cents, how much will 5 pens cost?", "options": ["$1.25", "$1", "$1.50", "$2"], "correct": 0 },
    { "question": "Which one of these is a geometric figure: Square, Circle, Rectangle, All of the above?", "options": ["All of the above", "Square", "Rectangle", "Circle"], "correct": 0 },
    { "question": "If a store sells 8 shirts for $40, what is the price of one shirt?", "options": ["$5", "$4", "$6", "$3"], "correct": 0 },
    { "question": "Which number completes the pattern: 1, 3, 6, 10, ?", "options": ["15", "14", "16", "12"], "correct": 0 },
    { "question": "What is the result of 8 + (3 × 2)?", "options": ["14", "16", "18", "15"], "correct": 0 },
    { "question": "If the time is 5:30 PM now, what will the time be after 2 hours and 45 minutes?", "options": ["8:15 PM", "8:30 PM", "9:15 PM", "9:30 PM"], "correct": 0 },
    { "question": "What comes next in the sequence: 1, 3, 5, 7, ?", "options": ["9", "8", "10", "11"], "correct": 0 },
    { "question": "If all oranges are fruits and all fruits grow on trees, can all oranges grow on trees?", "options": ["Yes", "No", "Not enough information", "Maybe"], "correct": 0 },
    { "question": "Which of the following numbers is divisible by both 2 and 3: 12, 16, 17, 18?", "options": ["12", "16", "17", "18"], "correct": 0 },
    { "question": "Which number is missing in the series: 2, 4, 8, 16, ?, 64", "options": ["32", "48", "36", "30"], "correct": 0 },
    { "question": "Which of the following is a prime number: 3, 4, 5, 6?", "options": ["3", "4", "5", "6"], "correct": 0 }
  ],

  funny: [
    { "question": "Why don't skeletons fight each other?", "options": ["They don't have the guts", "They are too lazy", "They are allergic to dust", "They don't know how to fight"], "correct": 0 },
    { "question": "What did one wall say to the other wall?", "options": ["I'll meet you at the corner", "You are looking great today", "Don't touch me", "We're in this together"], "correct": 0 },
    { "question": "Why can't your nose be 12 inches long?", "options": ["Because then it would be a foot", "Because it's too long", "Because it would look funny", "Because it's impossible"], "correct": 0 },
    { "question": "What did the grape do when it got stepped on?", "options": ["Nothing, it just let out a little wine", "It cried", "It rolled away", "It turned into a raisin"], "correct": 0 },
    { "question": "Why did the scarecrow win an award?", "options": ["Because he was outstanding in his field", "Because he was funny", "Because he could talk", "Because he was good at scaring crows"], "correct": 0 },
    { "question": "What do you call fake spaghetti?", "options": ["An impasta", "A noodle", "A pasta imposter", "A spaghetti wannabe"], "correct": 0 },
    { "question": "Why was the math book sad?", "options": ["Because it had too many problems", "Because it couldn't count", "Because it was full of equations", "Because it was too thick"], "correct": 0 },
    { "question": "What do you get when you cross a snowman and a vampire?", "options": ["Frostbite", "A cold heart", "A frozen vampire", "A snow vampire"], "correct": 0 },
    { "question": "Why don't eggs tell jokes?", "options": ["Because they might crack up", "Because they are shy", "Because they are too scrambled", "Because they are fragile"], "correct": 0 },
    { "question": "How do you organize a space party?", "options": ["You planet", "You make a plan", "You invite aliens", "You go to the moon"], "correct": 0 },
    { "question": "What do you call a pile of cats?", "options": ["A meowtain", "A catstack", "A furpile", "A clowder"], "correct": 0 },
    { "question": "Why did the bicycle fall over?", "options": ["Because it was two-tired", "Because it was unbalanced", "Because it was tired of riding", "Because it got sleepy"], "correct": 0 },
    { "question": "Why don't oysters donate to charity?", "options": ["Because they are shellfish", "Because they don't have wallets", "Because they are too shy", "Because they don't have enough money"], "correct": 0 },
    { "question": "What did the one hat say to the other hat?", "options": ["Stay here, I'm going on ahead", "I’m feeling a bit shady", "Let’s meet at the top", "You look good today"], "correct": 0 },
    { "question": "What do you call a sleeping bull?", "options": ["A bulldozer", "A sleepyhead", "A lazy cow", "A dreamer"], "correct": 0 },
    { "question": "Why do cows have hooves instead of feet?", "options": ["Because they lactose", "Because they like to moo", "Because they are too heavy", "Because they can't wear shoes"], "correct": 0 },
    { "question": "Why don't skeletons ever use cell phones?", "options": ["Because they don't have the bones to dial", "Because they are too busy scaring people", "Because they are dead", "Because they don't have hands"], "correct": 0 },
    { "question": "Why did the computer go to the doctor?", "options": ["Because it had a virus", "Because it was feeling a bit slow", "Because it needed a reboot", "Because it had a bug"], "correct": 0 },
    { "question": "Why don’t scientists trust atoms?", "options": ["Because they make up everything", "Because they are too small", "Because they are unpredictable", "Because they don't follow rules"], "correct": 0 },
    { "question": "Why did the coffee file a police report?", "options": ["Because it got mugged", "Because it was stolen", "Because it spilled", "Because it was too hot"], "correct": 0 },
    { "question": "What did the zero say to the eight?", "options": ["Nice belt!", "You look great", "What’s up", "You’ve got a nice curve"], "correct": 0 },
    { "question": "Why did the tomato blush?", "options": ["Because it saw the salad dressing", "Because it was ripe", "Because it was shy", "Because it got embarrassed"], "correct": 0 },
    { "question": "Why can't you trust stairs?", "options": ["They are always up to something", "They are always a bit wobbly", "They are always under construction", "Because they are always leading you down"], "correct": 0 },
    { "question": "What do you call cheese that isn't yours?", "options": ["Nacho cheese", "Cheddar cheese", "Your cheese", "Stolen cheese"], "correct": 0 },
    { "question": "Why do chicken coops only have two doors?", "options": ["Because if they had four, they’d be chicken sedans", "Because chickens don’t need more", "Because they are too small", "Because they only have two sides"], "correct": 0 },
    { "question": "What did the janitor say when he jumped out of the closet?", "options": ["Supplies!", "I’m here to clean", "You need to clean up", "I’m not hiding anymore"], "correct": 0 },
    { "question": "Why don’t some couples go to the gym?", "options": ["Because some relationships don’t work out", "Because they prefer Netflix", "Because they don’t have time", "Because they are not motivated"], "correct": 0 },
    { "question": "Why did the frog call his insurance company?", "options": ["He had a jump in his car", "He got in an accident", "He lost his wallet", "He needed a repair"], "correct": 0 },
    { "question": "What is a skeleton’s least favorite room in the house?", "options": ["The living room", "The kitchen", "The bathroom", "The dining room"], "correct": 0 },
    { "question": "Why did the pencil break up with the eraser?", "options": ["Because it had no point", "Because it was getting rubbed the wrong way", "Because it was tired of being erased", "Because they weren’t compatible"], "correct": 0 },
    { "question": "What do you call a fish with no eyes?", "options": ["A fsh", "A blind fish", "A fish without vision", "A lost fish"], "correct": 0 },
    { "question": "Why was the math book always stressed?", "options": ["Because it had too many problems", "Because it couldn’t solve anything", "Because it was too complicated", "Because it had too much to handle"], "correct": 0 },
    { "question": "What do you call a group of musical whales?", "options": ["An orca-stra", "A whale band", "A sea symphony", "A blue orchestra"], "correct": 0 },
    { "question": "Why was the stadium so hot?", "options": ["Because there were too many fans", "Because it was a hot day", "Because of all the cheering", "Because the players were too hot"], "correct": 0 },
    { "question": "Why did the banana go to the doctor?", "options": ["Because it wasn’t peeling well", "Because it had a bruise", "Because it was ripe", "Because it was sick"], "correct": 0 },
    { "question": "What did the cactus say to the cactus next to it?", "options": ["You’re looking prickly", "You’re my spiky friend", "Let’s stick together", "Stop poking me"], "correct": 0 },
    { "question": "What do you call a lazy kangaroo?", "options": ["A pouch potato", "A hopping sloth", "A relaxed jumper", "A kangaroo napper"], "correct": 0 },
    { "question": "Why don’t vampires like coffee?", "options": ["Because it’s too strong", "Because it keeps them awake", "Because it burns", "Because it doesn’t taste good"], "correct": 0 },
    { "question": "Why was the bicycle so slow?", "options": ["Because it was two-tired", "Because it didn’t have enough gears", "Because it was too heavy", "Because it needed air"], "correct": 0 },
    { "question": "What did the one ocean say to the other ocean?", "options": ["Nothing, they just waved", "I’m shore you’re fine", "I need to dive deep", "You’re looking salty"], "correct": 0 },
    { "question": "Why don’t we ever tell secrets at the beach?", "options": ["Because the sand will hear it", "Because it’s too windy", "Because there are too many people", "Because it’s too loud"], "correct": 0 }
  ],

  love: [
    { "question": "What is considered the universal symbol of love?", "options": ["Heart", "Rose", "Dove", "Cupid"], "correct": 0 },
    { "question": "Which day is celebrated as Valentine’s Day?", "options": ["14th February", "1st January", "25th December", "14th April"], "correct": 0 },
    { "question": "Which flower is most commonly associated with love?", "options": ["Tulip", "Rose", "Lily", "Orchid"], "correct": 1 },
    { "question": "What does 'Cupid' traditionally symbolize?", "options": ["War", "Friendship", "Love", "Happiness"], "correct": 2 },
    { "question": "Which Shakespeare play is known as the ultimate love story?", "options": ["Hamlet", "Macbeth", "Romeo and Juliet", "Othello"], "correct": 2 },
    { "question": "What color rose represents love?", "options": ["Yellow", "Red", "White", "Pink"], "correct": 1 },
    { "question": "What is the Greek god of love called?", "options": ["Ares", "Eros", "Hermes", "Apollo"], "correct": 1 },
    { "question": "Which romantic city is known as 'The City of Love'?", "options": ["Venice", "Paris", "Rome", "Barcelona"], "correct": 1 },
    { "question": "What is a love letter called in literature?", "options": ["Epistle", "Prose", "Sonnet", "Ode"], "correct": 0 },
    { "question": "What type of jewelry is most often given as a token of love?", "options": ["Bracelet", "Ring", "Earrings", "Necklace"], "correct": 1 },
    { "question": "Which love-themed movie features the line 'You complete me'?", "options": ["Titanic", "The Notebook", "Jerry Maguire", "Pretty Woman"], "correct": 2 },
    { "question": "What is the name of the Roman goddess of love?", "options": ["Minerva", "Venus", "Juno", "Diana"], "correct": 1 },
    { "question": "What is the term for a romantic walk taken by lovers?", "options": ["Stroll", "Promenade", "Date", "Amble"], "correct": 1 },
    { "question": "What is the main ingredient in a love potion in folklore?", "options": ["Chocolate", "Rose Petals", "Honey", "Wine"], "correct": 0 },
    { "question": "Which song by The Beatles claims 'All you need is love'?", "options": ["Hey Jude", "All You Need Is Love", "Let It Be", "Yesterday"], "correct": 1 },
    { "question": "Which famous monument in India was built as an act of love?", "options": ["Taj Mahal", "Red Fort", "Qutub Minar", "Lotus Temple"], "correct": 0 },
    { "question": "What is the traditional gift for a 25th wedding anniversary?", "options": ["Silver", "Gold", "Diamonds", "Pearls"], "correct": 0 },
    { "question": "Which color rose symbolizes friendship rather than love?", "options": ["Yellow", "Red", "White", "Pink"], "correct": 0 },
    { "question": "In which season do most weddings occur?", "options": ["Winter", "Spring", "Summer", "Fall"], "correct": 2 },
    { "question": "Which love-themed movie is set on the Titanic?", "options": ["The Notebook", "Romeo + Juliet", "Titanic", "Pride and Prejudice"], "correct": 2 },
    { "question": "What is the traditional symbol of Valentine’s Day?", "options": ["Cupid", "Heart", "Rose", "All of the above"], "correct": 3 },
    { "question": "Which romantic novel features Elizabeth Bennet and Mr. Darcy?", "options": ["Jane Eyre", "Pride and Prejudice", "Wuthering Heights", "Sense and Sensibility"], "correct": 1 },
    { "question": "Which gemstone is most associated with love?", "options": ["Emerald", "Ruby", "Diamond", "Sapphire"], "correct": 2 },
    { "question": "What is the term for love that is selfless and unconditional?", "options": ["Platonic", "Romantic", "Agape", "Infatuation"], "correct": 2 },
    { "question": "Which mythical creature is said to make people fall in love?", "options": ["Dragon", "Cupid", "Phoenix", "Unicorn"], "correct": 1 },
    { "question": "What type of love involves deep friendship and connection?", "options": ["Eros", "Storge", "Philia", "Ludus"], "correct": 2 },
    { "question": "Which romantic poet wrote 'Ode to a Nightingale'?", "options": ["John Keats", "William Wordsworth", "Lord Byron", "Percy Shelley"], "correct": 0 },
    { "question": "Which love-themed dance is traditionally performed in pairs?", "options": ["Tango", "Ballet", "Jazz", "Salsa"], "correct": 0 },
    { "question": "Which country invented the tradition of engagement rings?", "options": ["Italy", "France", "Germany", "Austria"], "correct": 2 },
    { "question": "What is the shape most associated with love?", "options": ["Square", "Circle", "Triangle", "Heart"], "correct": 3 },
    { "question": "What is a love triangle?", "options": ["Three friends", "Three people romantically involved", "Three rivals", "Three family members"], "correct": 1 }
  ]


};
